### PR TITLE
Added related ESLint (linter) and Prettier (code formatting) files and formatted existing code

### PR DESCRIPTION
**Pull request by lecegues**
- Similar config files for both frontend/ and backend/ 
- .prettierignore files: files to ignore formatting
- package.json: new modules & scripts introduced to run linter and prettier
- Add a lint step when building in CI Pipeline
- Lint & Format all existing code

### CODE REVIEW

**Review by funmise — APPROVED** [review]
Good work, a few rule in the linting configuration might be unnecessary.

**Review by brj496 — APPROVED** [review]
Looks good, nothing that I have any issues with.

**Comment by lecegues** [comment]
> Good work, a few rule in the linting configuration might be unnecessary.

Which rules?

**Comment by funmise** [comment]
> > Good work, a few rule in the linting configuration might be unnecessary.
> 
> Which rules?

usetabs and tabwidth. do we need both?

**Comment by lecegues** [comment]
> > > Good work, a few rule in the linting configuration might be unnecessary.
> > 
> > 
> > Which rules?
> 
> usetabs and tabwidth. do we need both?

Yes, you are correct. TabWidth is not needed if `useTabs = true`. I have removed it in my most recent commit.

**Pull request merged**
